server:
  port: 8080

app:
  config:
    keycloak:
      url: http://localhost:8571/
      realm: banking-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/api/fund-transfers/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: sequence-generator
          uri: lb://sequence-generator
          predicates:
            - Path=/sequence/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/fund-transfers/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${app.config.keycloak.url}realms/${app.config.keycloak.realm}
        registration:
          keycloak:
            provider: keycloak
            client-id: banking-app
            client-secret: your-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      resourceserver:
        jwt:
          issuer-uri: ${app.config.keycloak.url}realms/${app.config.keycloak.realm}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

