server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Keycloak Configuration
keycloak:
  auth-server-url: http://localhost:8571/
  realm: banking-service
  resource: banking-service-client
  credentials:
    secret: your-client-secret
  admin:
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.training.user.service: DEBUG
    org.hibernate.SQL: DEBUG

